name: Manual APK Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: "Build Type"
        required: true
        default: "debug"
        type: choice
        options:
          - debug
          - release
      upload_artifacts:
        description: "Upload artifacts"
        required: false
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"

      - name: Install dependencies
        run: flutter pub get

      - name: Generate build files
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK (Debug)
        if: ${{ github.event.inputs.build_type == 'debug' }}
        run: flutter build apk --debug

      - name: Build APK (Release)
        if: ${{ github.event.inputs.build_type == 'release' }}
        run: flutter build apk --release

      - name: Build AAB (Release)
        if: ${{ github.event.inputs.build_type == 'release' }}
        run: flutter build appbundle --release

      - name: Upload Debug APK
        if: ${{ github.event.inputs.build_type == 'debug' && github.event.inputs.upload_artifacts == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: metro-mate-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload Release APK
        if: ${{ github.event.inputs.build_type == 'release' && github.event.inputs.upload_artifacts == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: metro-mate-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Release AAB
        if: ${{ github.event.inputs.build_type == 'release' && github.event.inputs.upload_artifacts == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: metro-mate-release-aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Display APK size (Release)
        if: ${{ github.event.inputs.build_type == 'release' }}
        run: |
          APK_SIZE=$(ls -lh build/app/outputs/flutter-apk/app-release.apk | awk '{print $5}')
          echo "### APK Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Type**: Release" >> $GITHUB_STEP_SUMMARY
          echo "- **APK Size**: $APK_SIZE" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Date**: $(date)" >> $GITHUB_STEP_SUMMARY

      - name: Display APK size (Debug)
        if: ${{ github.event.inputs.build_type == 'debug' }}
        run: |
          APK_SIZE=$(ls -lh build/app/outputs/flutter-apk/app-debug.apk | awk '{print $5}')
          echo "### APK Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Type**: Debug" >> $GITHUB_STEP_SUMMARY
          echo "- **APK Size**: $APK_SIZE" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Date**: $(date)" >> $GITHUB_STEP_SUMMARY
